package edu.iust.advancejava.streams.problems;

import java.util.function.Function;
import java.util.stream.Stream;

public class Factorial {

    public static Stream<Long> stream(){
        /* iterate method takes a seed value and a  function. A seed is the first element of the stream.
        The second element is generated by applying the function  to the first element.
        The third element is generated by applying the function on the second element.
         */
        return Stream.iterate(new Pair<>(1L, 1L),
                pair -> new Pair<>(pair.getFirst() + 1, pair.getSecond() * (pair.getFirst() + 1)))
                .map(Pair::getSecond);
    }

}
